apiVersion: apps/v1
kind: Deployment
metadata:
  name: converter
spec:
  replicas: 2
  selector:
    matchLabels:
      components: backend
  template:
    metadata:
      name: converter
      labels:
        components: backend
    spec:
      containers:
        - name: converter
          image: antonlarichev/conv-service:1.0
          ports:
            - containerPort: 3080
          resources:
            requests:
              memory: 256Mi
              cpu: 100m
            limits:
              memory: 256Mi
              cpu: 100m
          envFrom:
            - secretRef:
                name: conv-secret
