name: conv-app
replicas: 2
components: frontend
app:
  image: antonlarichev/conv-app
  version: "1.2"
  ports: 80
  resources:
    requests:
      memory: 128Mi
      cpu: 50m
    limits:
      memory: 256Mi
      cpu: 100m
host: conv.test
configname: conv-config
